#define _DEFAULT_SOURCE
#define _BSD_SOURCE
#define _XOPEN_SOURCE 600

#define DATA_LAYER_FILENO
#include <time.h>
#include <sys/time.h>
#include <stdlib.h>
#include <ftw.h>
#include "util.c"
#include "abstract_data_layer.c"

extern const char *demo0;
extern const char *demo1;
extern const char *demo2;
extern const char *demo3;
extern const char *demo4;

static int unlink_cb(const char *fpath, const struct stat *sb, int typeflag, struct FTW *ftwbuf) {
	int rv = remove(fpath);

	if (rv) perror(fpath);

	return rv;
}

static inline int rmrf(const char *path) {
	return nftw(path, unlink_cb, 64, FTW_DEPTH | FTW_PHYS);
}

const char *addr;
static int nop(struct layer_context *con, const char *error) {
	printf("Failed to insert new record. Reason: %s\n", error);
	deinitialize_engine(ENGINE_FILENO, con);
	rmrf(addr);
	return EXIT_FAILURE;
}

int randfd;
void rfill(void *ptr, size_t size) {
	ssize_t got = read(randfd, ptr, size);
	if (got < 0) unsafe_rand(ptr, size);
}

int main(int argc, char **argv) {
	if (argc < 2) {
		return printf("You should specify the path to testdata. Example:\n./demo demo_data\n");
	}

	randfd = open("/dev/urandom", O_RDONLY);
	if (randfd < 0) return EXIT_FAILURE;

	addr = argv[1];

	if (mkdir(addr, 0777) != 0) {
		return printf("Failed to create a directory (%s) for demo data: %s\n", addr, strerror(errno));
	}

	struct layer_context con;
	const char *error;
	struct data_layer d = {.e = ENGINE_FILENO, .addr = addr, .context = &con, .randfun = rfill};
	if (initialize_engine(&d, &error) == false) {
		printf("Failed to initialize engine: %s\n", error);
		return EXIT_FAILURE;
	}

	char buffer[35250];

	struct blog_record b[5] = {
		{.stack = buffer, .stack_space = sizeof(buffer), .display = DISPLAY_SOURCE},
		{.stack = buffer, .stack_space = sizeof(buffer), .display = DISPLAY_SOURCE},
		{.stack = buffer, .stack_space = sizeof(buffer), .display = DISPLAY_SOURCE},
		{.stack = buffer, .stack_space = sizeof(buffer), .display = DISPLAY_SOURCE},
		{.stack = buffer, .stack_space = sizeof(buffer), .display = DISPLAY_SOURCE}
	};

	char *tags0[] = {"life", NULL};
	b[0].title = "Literally start of your life";
	b[0].titlelen = strlen(b[0].title);
	b[0].data = demo0;
	b[0].datalen = strlen(demo0);
	b[0].tags = tags0;


	char *tags1[] = {"evil", "escape", NULL};
	b[1].title = "Escaping from the evil";
	b[1].titlelen = strlen(b[1].title);
	b[1].data = demo1;
	b[1].datalen = strlen(demo1);
	b[1].tags = tags1;


	char *tags2[] = {"island", NULL};
	b[2].title = "Desert island";
	b[2].titlelen = strlen(b[2].title);
	b[2].data = demo2;
	b[2].datalen = strlen(demo2);
	b[2].tags = tags2;


	char *tags3[] = {"island", NULL};
	b[3].title = "Empty island";
	b[3].titlelen = strlen(b[3].title);
	b[3].data = demo3;
	b[3].datalen = strlen(demo3);
	b[3].tags = tags3;


	char *tags4[] = {"story", NULL};
	b[4].title = "Shipwrecked during a dreadful storm";
	b[4].titlelen = strlen(b[4].title);
	b[4].data = demo4;
	b[4].datalen = strlen(demo4);
	b[4].tags = tags4;


	if (insert_record(b + 0, &con, &error) == false) return nop(&con, error);
	if (insert_record(b + 1, &con, &error) == false) return nop(&con, error);
	if (insert_record(b + 2, &con, &error) == false) return nop(&con, error);
	if (insert_record(b + 3, &con, &error) == false) return nop(&con, error);
	if (insert_record(b + 4, &con, &error) == false) return nop(&con, error);

	struct usr u = {
		.id = 1,
		.display_name = "Kind admin",
		.email = "dasdas@asdas.com",
		.credentials = "DJASKODJASDHAS",
		.status = ACTIVE,
		.create_time.t = 981239128,
		.approve_code = "12345",
		.expiration.approve_code_expiration.t = 7897897,
	};
	struct user_action action = {.operation = ADD};
	if (user(&u, action, &con, &error) == false) return nop(&con, error);

	puts("Done!");

	return EXIT_SUCCESS;
}

const char *demo0 = "## CHAPTER I. START IN LIFE\n\n"
					"\n"
					"I was born in the year 1632, in the city of York, of a good family, though not of that country:\n"
					"1. my father being a foreigner of Bremen\n"
					"2. who settled first at Hull.\n"
					"\n\n"
					"He got a ***good*** estate by merchandise, and leaving off his trade, lived afterwards at York, from whence he had married my mother, whose relations were named Robinson, a very good family in that country, and from whom I was called Robinson Kreutznaer; but, by the usual corruption of words in England, we are now called—nay we call ourselves and write our name—Crusoe; and so my companions always called me.\n\n"
					"I had two elder brothers, one of whom was lieutenant-colonel to an English regiment of foot in Flanders, formerly commanded by the famous Colonel Lockhart, and was killed at the battle near Dunkirk against the Spaniards. What became of my second brother I never knew, any more than my father or mother knew what became of me. \n\n"
					"---\nBeing the third son of the family and not bred to any trade, my head began to be filled very early with rambling thoughts. My father, who was very ancient, had given me a competent share of learning, as far as house-education and a country free school generally go, and designed me for the law; but I would be satisfied with nothing but going to sea; and my inclination to this led me so strongly against the will, nay, the commands of my father, and against all the entreaties and persuasions of my mother and other friends, that there seemed to be something fatal in that propensity of nature, tending directly to the life of misery which was to befall me.\n\n"
					"My father, a wise and grave man, gave me serious and excellent counsel against what he foresaw was my design. He called me one morning into his chamber, where he was confined by the gout, and expostulated very warmly with me upon this subject. He asked me what reasons, more than a mere wandering inclination, I had for leaving father’s house and my native country, where I might be well introduced, and had a prospect of raising my fortune by application and industry, with a life of ease and pleasure. He told me it was men of desperate fortunes on one hand, or of aspiring, superior fortunes on the other, who went abroad upon adventures, to rise by enterprise, and make themselves famous in undertakings of a nature out of the common road; that these things were all either too far above me or too far below me; that mine was the middle state, or what might be called the upper station of low life, which he had found, by long experience, was the best state in the world, the most suited to human happiness, not exposed to the miseries and hardships, the labour and sufferings of the mechanic part of mankind, and not embarrassed with the pride, luxury, ambition, and envy of the upper part of mankind. He told me I might judge of the happiness of this state by this one thing—viz. that this was the state of life which all other people envied; that kings have frequently lamented the miserable consequence of being born to great things, and wished they had been placed in the middle of the two extremes, between the mean and the great; that the wise man gave his testimony to this, as the standard of felicity, when he prayed to have neither poverty nor riches.\n\n"
					"He bade me observe it, and I should always find that the calamities of life were shared among the upper and lower part of mankind, but that the middle station had the fewest disasters, and was not exposed to so many vicissitudes as the higher or lower part of mankind; nay, they were not subjected to so many distempers and uneasinesses, either of body or mind, as those were who, by vicious living, luxury, and extravagances on the one hand, or by hard labour, want of necessaries, and mean or insufficient diet on the other hand, bring distemper upon themselves by the natural consequences of their way of living; that the middle station of life was calculated for all kind of virtue and all kind of enjoyments; that peace and plenty were the handmaids of a middle fortune; that temperance, moderation, quietness, health, society, all agreeable diversions, and all desirable pleasures, were the blessings attending the middle station of life; that this way men went silently and smoothly through the world, and comfortably out of it, not embarrassed with the labours of the hands or of the head, not sold to a life of slavery for daily bread, nor harassed with perplexed circumstances, which rob the soul of peace and the body of rest, nor enraged with the passion of envy, or the secret burning lust of ambition for great things; but, in easy circumstances, sliding gently through the world, and sensibly tasting the sweets of living, without the bitter; feeling that they are happy, and learning by every day’s experience to know it more sensibly.\n\n"
					"After this he pressed me earnestly, and in the most affectionate manner, not to play the young man, nor to precipitate myself into miseries which nature, and the station of life I was born in, seemed to have provided against; that I was under no necessity of seeking my bread; that he would do well for me, and endeavour to enter me fairly into the station of life which he had just been recommending to me; and that if I was not very easy and happy in the world, it must be my mere fate or fault that must hinder it; and that he should have nothing to answer for, having thus discharged his duty in warning me against measures which he knew would be to my hurt; in a word, that as he would do very kind things for me if I would stay and settle at home as he directed, so he would not have so much hand in my misfortunes as to give me any encouragement to go away; and to close all, he told me I had my elder brother for an example, to whom he had used the same earnest persuasions to keep him from going into the Low Country wars, but could not prevail, his young desires prompting him to run into the army, where he was killed; and though he said he would not cease to pray for me, yet he would venture to say to me, that if I did take this foolish step, God would not bless me, and I should have leisure hereafter to reflect upon having neglected his counsel when there might be none to assist in my recovery.\n\n"
					"I observed in this last part of his discourse, which was truly prophetic, though I suppose my father did not know it to be so himself—I say, I observed the tears run down his face very plentifully, especially when he spoke of my brother who was killed: and that when he spoke of my having leisure to repent, and none to assist me, he was so moved that he broke off the discourse, and told me his heart was so full he could say no more to me.\n\n"
					"I was sincerely affected with this discourse, and, indeed, who could be otherwise? and I resolved not to think of going abroad any more, but to settle at home according to my father’s desire. But alas! a few days wore it all off; and, in short, to prevent any of my father’s further importunities, in a few weeks after I resolved to run quite away from him. However, I did not act quite so hastily as the first heat of my resolution prompted; but I took my mother at a time when I thought her a little more pleasant than ordinary, and told her that my thoughts were so entirely bent upon seeing the world that I should never settle to anything with resolution enough to go through with it, and my father had better give me his consent than force me to go without it; that I was now eighteen years old, which was too late to go apprentice to a trade or clerk to an attorney; that I was sure if I did I should never serve out my time, but I should certainly run away from my master before my time was out, and go to sea; and if she would speak to my father to let me go one voyage abroad, if I came home again, and did not like it, I would go no more; and I would promise, by a double diligence, to recover the time that I had lost.\n\n"
					"This put my mother into a great passion; she told me she knew it would be to no purpose to speak to my father upon any such subject; that he knew too well what was my interest to give his consent to anything so much for my hurt; and that she wondered how I could think of any such thing after the discourse I had had with my father, and such kind and tender expressions as she knew my father had used to me; and that, in short, if I would ruin myself, there was no help for me; but I might depend I should never have their consent to it; that for her part she would not have so much hand in my destruction; and I should never have it to say that my mother was willing when my father was not.\n\n"
					"Though my mother refused to move it to my father, yet I heard afterwards that she reported all the discourse to him, and that my father, after showing a great concern at it, said to her, with a sigh, “That boy might be happy if he would stay at home; but if he goes abroad, he will be the most miserable wretch that ever was born: I can give no consent to it.”\n\n"
					"It was not till almost a year after this that I broke loose, though, in the meantime, I continued obstinately deaf to all proposals of settling to business, and frequently expostulated with my father and mother about their being so positively determined against what they knew my inclinations prompted me to. But being one day at Hull, where I went casually, and without any purpose of making an elopement at that time; but, I say, being there, and one of my companions being about to sail to London in his father’s ship, and prompting me to go with them with the common allurement of seafaring men, that it should cost me nothing for my passage, I consulted neither father nor mother any more, nor so much as sent them word of it; but leaving them to hear of it as they might, without asking God’s blessing or my father’s, without any consideration of circumstances or consequences, and in an ill hour, God knows, on the 1st of September 1651, I went on board a ship bound for London. Never any young adventurer’s misfortunes, I believe, began sooner, or continued longer than mine. The ship was no sooner out of the Humber than the wind began to blow and the sea to rise in a most frightful manner; and, as I had never been at sea before, I was most inexpressibly sick in body and terrified in mind. I began now seriously to reflect upon what I had done, and how justly I was overtaken by the judgment of Heaven for my wicked leaving my father’s house, and abandoning my duty. All the good counsels of my parents, my father’s tears and my mother’s entreaties, came now fresh into my mind; and my conscience, which was not yet come to the pitch of hardness to which it has since, reproached me with the contempt of advice, and the breach of my duty to God and my father.\n\n"
					"All this while the storm increased, and the sea went very high, though nothing like what I have seen many times since; no, nor what I saw a few days after; but it was enough to affect me then, who was but a young sailor, and had never known anything of the matter. I expected every wave would have swallowed us up, and that every time the ship fell down, as I thought it did, in the trough or hollow of the sea, we should never rise more; in this agony of mind, I made many vows and resolutions that if it would please God to spare my life in this one voyage, if ever I got once my foot upon dry land again, I would go directly home to my father, and never set it into a ship again while I lived; that I would take his advice, and never run myself into such miseries as these any more. Now I saw plainly the goodness of his observations about the middle station of life, how easy, how comfortably he had lived all his days, and never had been exposed to tempests at sea or troubles on shore; and I resolved that I would, like a true repenting prodigal, go home to my father.\n\n"
					"These wise and sober thoughts continued all the while the storm lasted, and indeed some time after; but the next day the wind was abated, and the sea calmer, and I began to be a little inured to it; however, I was very grave for all that day, being also a little sea-sick still; but towards night the weather cleared up, the wind was quite over, and a charming fine evening followed; the sun went down perfectly clear, and rose so the next morning; and having little or no wind, and a smooth sea, the sun shining upon it, the sight was, as I thought, the most delightful that ever I saw.\n";

const char *demo1 = "## CHAPTER II. SLAVERY AND ESCAPE\n\n"
					"That *evil* influence which carried me first away from my father’s house—which hurried me into the wild and indigested notion of raising my fortune, and that impressed those conceits so forcibly upon me as to make me deaf to all good advice, and to the entreaties and even the commands of my father—I say, the same influence, whatever it was, presented the most unfortunate of all enterprises to my view; and I went on board a vessel bound to the coast of Africa; or, as our sailors vulgarly called it, a voyage to Guinea. \n\n"
					"It was my great misfortune that:\n"
					"1. in all these adventures I did not ship myself as a sailor\n"
					"2. when, though I might indeed have worked a little harder than ordinary\n"
					"\n"
					"Yet at the same time I should have learnt the duty and office of a fore-mast man, and in time might have qualified myself for a mate or lieutenant, if not for a master. But as it was always my fate to choose for the worse, so I did here; for having money in my pocket and good clothes upon my back, I would always go on board in the habit of a gentleman; and so I neither had any business in the ship, nor learned to do any. \n\n"
					"It was my lot first of all to fall into pretty good company in London, which does not always happen to such loose and misguided young fellows as I then was; the devil generally not omitting to lay some snare for them very early; but it was not so with me. I first got acquainted with the master of a ship who had been on the coast of Guinea; and who, having had very good success there, was resolved to go again. This captain taking a fancy to my conversation, which was not at all disagreeable at that time, hearing me say I had a mind to see the world, told me if I would go the voyage with him I should be at no expense; I should be his messmate and his companion; and if I could carry anything with me, I should have all the advantage of it that the trade would admit; and perhaps I might meet with some encouragement. \n\n"
					"I embraced the offer; and entering into a strict friendship with this captain, who was an honest, plain-dealing man, I went the voyage with him, and carried a small adventure with me, which, by the disinterested honesty of my friend the captain, I increased very considerably; for I carried about £40 in such toys and trifles as the captain directed me to buy. These £40 I had mustered together by the assistance of some of my relations whom I corresponded with; and who, I believe, got my father, or at least my mother, to contribute so much as that to my first adventure. \n\n"
					"---\nThis was the only voyage which I may say was successful in all my adventures, which I owe to the integrity and honesty of my friend the captain; under whom also I got a competent knowledge of the mathematics and the rules of navigation, learned how to keep an account of the ship’s course, take an observation, and, in short, to understand some things that were needful to be understood by a sailor; for, as he took delight to instruct me, I took delight to learn; and, in a word, this voyage made me both a sailor and a merchant; for I brought home five pounds nine ounces of gold-dust for my adventure, which yielded me in London, at my return, almost £300; and this filled me with those aspiring thoughts which have since so completed my ruin. \n\n"
					"Yet even in this voyage I had my misfortunes too; particularly, that I was continually sick, being thrown into a violent calenture by the excessive heat of the climate; our principal trading being upon the coast, from latitude of 15 degrees north even to the line itself. \n\n"
					"I was now set up for a Guinea trader; and my friend, to my great misfortune, dying soon after his arrival, I resolved to go the same voyage again, and I embarked in the same vessel with one who was his mate in the former voyage, and had now got the command of the ship. This was the unhappiest voyage that ever man made; for though I did not carry quite £100 of my new-gained wealth, so that I had £200 left, which I had lodged with my friend’s widow, who was very just to me, yet I fell into terrible misfortunes. The first was this: our ship making her course towards the Canary Islands, or rather between those islands and the African shore, was surprised in the grey of the morning by a Turkish rover of Sallee, who gave chase to us with all the sail she could make. We crowded also as much canvas as our yards would spread, or our masts carry, to get clear; but finding the pirate gained upon us, and would certainly come up with us in a few hours, we prepared to fight; our ship having twelve guns, and the rogue eighteen. About three in the afternoon he came up with us, and bringing to, by mistake, just athwart our quarter, instead of athwart our stern, as he intended, we brought eight of our guns to bear on that side, and poured in a broadside upon him, which made him sheer off again, after returning our fire, and pouring in also his small shot from near two hundred men which he had on board. However, we had not a man touched, all our men keeping close. He prepared to attack us again, and we to defend ourselves. But laying us on board the next time upon our other quarter, he entered sixty men upon our decks, who immediately fell to cutting and hacking the sails and rigging. We plied them with small shot, half-pikes, powder-chests, and such like, and cleared our deck of them twice. However, to cut short this melancholy part of our story, our ship being disabled, and three of our men killed, and eight wounded, we were obliged to yield, and were carried all prisoners into Sallee, a port belonging to the Moors. \n\n"
					"The usage I had there was not so dreadful as at first I apprehended; nor was I carried up the country to the emperor’s court, as the rest of our men were, but was kept by the captain of the rover as his proper prize, and made his slave, being young and nimble, and fit for his business. At this surprising change of my circumstances, from a merchant to a miserable slave, I was perfectly overwhelmed; and now I looked back upon my father’s prophetic discourse to me, that I should be miserable and have none to relieve me, which I thought was now so effectually brought to pass that I could not be worse; for now the hand of Heaven had overtaken me, and I was undone without redemption; but, alas! this was but a taste of the misery I was to go through, as will appear in the sequel of this story. \n\n"
					"As my new patron, or master, had taken me home to his house, so I was in hopes that he would take me with him when he went to sea again, believing that it would some time or other be his fate to be taken by a Spanish or Portugal man-of-war; and that then I should be set at liberty. But this hope of mine was soon taken away; for when he went to sea, he left me on shore to look after his little garden, and do the common drudgery of slaves about his house; and when he came home again from his cruise, he ordered me to lie in the cabin to look after the ship. \n\n"
					"Here I meditated nothing but my escape, and what method I might take to effect it, but found no way that had the least probability in it; nothing presented to make the supposition of it rational; for I had nobody to communicate it to that would embark with me—no fellow-slave, no Englishman, Irishman, or Scotchman there but myself; so that for two years, though I often pleased myself with the imagination, yet I never had the least encouraging prospect of putting it in practice.\n\n"
					"After about two years, an odd circumstance presented itself, which put the old thought of making some attempt for my liberty again in my head. My patron lying at home longer than usual without fitting out his ship, which, as I heard, was for want of money, he used constantly, once or twice a week, sometimes oftener if the weather was fair, to take the ship’s pinnace and go out into the road a-fishing; and as he always took me and young Maresco with him to row the boat, we made him very merry, and I proved very dexterous in catching fish; insomuch that sometimes he would send me with a Moor, one of his kinsmen, and the youth—the Maresco, as they called him—to catch a dish of fish for him.\n\n"
					"It happened one time, that going a-fishing in a calm morning, a fog rose so thick that, though we were not half a league from the shore, we lost sight of it; and rowing we knew not whither or which way, we laboured all day, and all the next night; and when the morning came we found we had pulled off to sea instead of pulling in for the shore; and that we were at least two leagues from the shore. However, we got well in again, though with a great deal of labour and some danger; for the wind began to blow pretty fresh in the morning; but we were all very hungry.\n\n"
					"But our patron, warned by this disaster, resolved to take more care of himself for the future; and having lying by him the longboat of our English ship that he had taken, he resolved he would not go a-fishing any more without a compass and some provision; so he ordered the carpenter of his ship, who also was an English slave, to build a little state-room, or cabin, in the middle of the long-boat, like that of a barge, with a place to stand behind it to steer, and haul home the main-sheet; the room before for a hand or two to stand and work the sails. She sailed with what we call a shoulder-of-mutton sail; and the boom jibed over the top of the cabin, which lay very snug and low, and had in it room for him to lie, with a slave or two, and a table to eat on, with some small lockers to put in some bottles of such liquor as he thought fit to drink; and his bread, rice, and coffee.\n\n"
					"We went frequently out with this boat a-fishing; and as I was most dexterous to catch fish for him, he never went without me. It happened that he had appointed to go out in this boat, either for pleasure or for fish, with two or three Moors of some distinction in that place, and for whom he had provided extraordinarily, and had, therefore, sent on board the boat overnight a larger store of provisions than ordinary; and had ordered me to get ready three fusees with powder and shot, which were on board his ship, for that they designed some sport of fowling as well as fishing.\n\n"
					"I got all things ready as he had directed, and waited the next morning with the boat washed clean, her ancient and pendants out, and everything to accommodate his guests; when by-and-by my patron came on board alone, and told me his guests had put off going from some business that fell out, and ordered me, with the man and boy, as usual, to go out with the boat and catch them some fish, for that his friends were to sup at his house, and commanded that as soon as I got some fish I should bring it home to his house; all which I prepared to do.\n\n"
					"This moment my former notions of deliverance darted into my thoughts, for now I found I was likely to have a little ship at my command; and my master being gone, I prepared to furnish myself, not for fishing business, but for a voyage; though I knew not, neither did I so much as consider, whither I should steer—anywhere to get out of that place was my desire. \n\n"
					"My first contrivance was to make a pretence to speak to this Moor, to get something for our subsistence on board; for I told him we must not presume to eat of our patron’s bread. He said that was true; so he brought a large basket of rusk or biscuit, and three jars of fresh water, into the boat. I knew where my patron’s case of bottles stood, which it was evident, by the make, were taken out of some English prize, and I conveyed them into the boat while the Moor was on shore, as if they had been there before for our master. I conveyed also a great lump of beeswax into the boat, which weighed about half a hundred-weight, with a parcel of twine or thread, a hatchet, a saw, and a hammer, all of which were of great use to us afterwards, especially the wax, to make candles. Another trick I tried upon him, which he innocently came into also: his name was Ismael, which they call Muley, or Moely; so I called to him—“Moely,” said I, “our patron’s guns are on board the boat; can you not get a little powder and shot? It may be we may kill some alcamies (a fowl like our curlews) for ourselves, for I know he keeps the gunner’s stores in the ship.” “Yes,” says he, “I’ll bring some;” and accordingly he brought a great leather pouch, which held a pound and a half of powder, or rather more; and another with shot, that had five or six pounds, with some bullets, and put all into the boat. At the same time I had found some powder of my master’s in the great cabin, with which I filled one of the large bottles in the case, which was almost empty, pouring what was in it into another; and thus furnished with everything needful, we sailed out of the port to fish. The castle, which is at the entrance of the port, knew who we were, and took no notice of us; and we were not above a mile out of the port before we hauled in our sail and set us down to fish. The wind blew from the N.N.E., which was contrary to my desire, for had it blown southerly I had been sure to have made the coast of Spain, and at least reached to the bay of Cadiz; but my resolutions were, blow which way it would, I would be gone from that horrid place where I was, and leave the rest to fate.\n\n";
const char *demo2 = "## CHAPTER III. WRECKED ON A DESERT ISLAND\n\n"
					"\n"
					"After this stop, we made on to the southward continually for ten or twelve days, living very sparingly on our provisions, which began to abate very much, and going no oftener to the shore than we were obliged to for fresh water. My design in this was to make the river Gambia or Senegal, that is to say anywhere about the Cape de Verde, where I was in hopes to meet with some European ship; and if I did not, I knew not what course I had to take, but to seek for the islands, or perish there among the negroes. I knew that all the ships from Europe, which sailed either to the coast of Guinea or to Brazil, or to the East Indies, made this cape, or those islands; and, in a word, I put the whole of my fortune upon this single point, either that I must meet with some ship or must perish. \n"
					"When I had pursued this resolution about ten days longer, as I have said, I began to see that the land was inhabited; and in two or three places, as we sailed by, we saw people stand upon the shore to look at us; we could also perceive they were quite black and naked. I was once inclined to have gone on shore to them; but Xury was my better counsellor, and said to me, “No go, no go.” However, I hauled in nearer the shore that I might talk to them, and I found they ran along the shore by me a good way. I observed they had no weapons in their hand, except one, who had a long slender stick, which Xury said was a lance, and that they could throw them a great way with good aim; so I kept at a distance, but talked with them by signs as well as I could; and particularly made signs for something to eat: they beckoned to me to stop my boat, and they would fetch me some meat. Upon this I lowered the top of my sail and lay by, and two of them ran up into the country, and in less than half-an-hour came back, and brought with them two pieces of dried flesh and some corn, such as is the produce of their country; but we neither knew what the one or the other was; however, we were willing to accept it, but how to come at it was our next dispute, for I would not venture on shore to them, and they were as much afraid of us; but they took a safe way for us all, for they brought it to the shore and laid it down, and went and stood a great way off till we fetched it on board, and then came close to us again. \n"
					"\n---\nWe made signs of thanks to them, for we had nothing to make them amends; but an opportunity offered that very instant to oblige them wonderfully; for while we were lying by the shore came two mighty creatures, one pursuing the other (as we took it) with great fury from the mountains towards the sea; whether it was the male pursuing the female, or whether they were in sport or in rage, we could not tell, any more than we could tell whether it was usual or strange, but I believe it was the latter; because, in the first place, those ravenous creatures seldom appear but in the night; and, in the second place, we found the people terribly frighted, especially the women. The man that had the lance or dart did not fly from them, but the rest did; however, as the two creatures ran directly into the water, they did not offer to fall upon any of the negroes, but plunged themselves into the sea, and swam about, as if they had come for their diversion; at last one of them began to come nearer our boat than at first I expected; but I lay ready for him, for I had loaded my gun with all possible expedition, and bade Xury load both the others. As soon as he came fairly within my reach, I fired, and shot him directly in the head; immediately he sank down into the water, but rose instantly, and plunged up and down, as if he were struggling for life, and so indeed he was; he immediately made to the shore; but between the wound, which was his mortal hurt, and the strangling of the water, he died just before he reached the shore. \n"
					"It is impossible to express the astonishment of these poor creatures at the noise and fire of my gun: some of them were even ready to die for fear, and fell down as dead with the very terror; but when they saw the creature dead, and sunk in the water, and that I made signs to them to come to the shore, they took heart and came, and began to search for the creature. I found him by his blood staining the water; and by the help of a rope, which I slung round him, and gave the negroes to haul, they dragged him on shore, and found that it was a most curious leopard, spotted, and fine to an admirable degree; and the negroes held up their hands with admiration, to think what it was I had killed him with. \n"
					"The other creature, frighted with the flash of fire and the noise of the gun, swam on shore, and ran up directly to the mountains from whence they came; nor could I, at that distance, know what it was. I found quickly the negroes wished to eat the flesh of this creature, so I was willing to have them take it as a favour from me; which, when I made signs to them that they might take him, they were very thankful for. Immediately they fell to work with him; and though they had no knife, yet, with a sharpened piece of wood, they took off his skin as readily, and much more readily, than we could have done with a knife. They offered me some of the flesh, which I declined, pointing out that I would give it them; but made signs for the skin, which they gave me very freely, and brought me a great deal more of their provisions, which, though I did not understand, yet I accepted. I then made signs to them for some water, and held out one of my jars to them, turning it bottom upward, to show that it was empty, and that I wanted to have it filled. They called immediately to some of their friends, and there came two women, and brought a great vessel made of earth, and burnt, as I supposed, in the sun, this they set down to me, as before, and I sent Xury on shore with my jars, and filled them all three. The women were as naked as the men. \n"
					"I was now furnished with roots and corn, such as it was, and water; and leaving my friendly negroes, I made forward for about eleven days more, without offering to go near the shore, till I saw the land run out a great length into the sea, at about the distance of four or five leagues before me; and the sea being very calm, I kept a large offing to make this point. At length, doubling the point, at about two leagues from the land, I saw plainly land on the other side, to seaward; then I concluded, as it was most certain indeed, that this was the Cape de Verde, and those the islands called, from thence, Cape de Verde Islands. However, they were at a great distance, and I could not well tell what I had best to do; for if I should be taken with a fresh of wind, I might neither reach one or other. \n"
					"In this dilemma, as I was very pensive, I stepped into the cabin and sat down, Xury having the helm; when, on a sudden, the boy cried out, “Master, master, a ship with a sail!” and the foolish boy was frighted out of his wits, thinking it must needs be some of his master’s ships sent to pursue us, but I knew we were far enough out of their reach. I jumped out of the cabin, and immediately saw, not only the ship, but that it was a Portuguese ship; and, as I thought, was bound to the coast of Guinea, for negroes. But, when I observed the course she steered, I was soon convinced they were bound some other way, and did not design to come any nearer to the shore; upon which I stretched out to sea as much as I could, resolving to speak with them if possible. \n"
					"With all the sail I could make, I found I should not be able to come in their way, but that they would be gone by before I could make any signal to them: but after I had crowded to the utmost, and began to despair, they, it seems, saw by the help of their glasses that it was some European boat, which they supposed must belong to some ship that was lost; so they shortened sail to let me come up. I was encouraged with this, and as I had my patron’s ancient on board, I made a waft of it to them, for a signal of distress, and fired a gun, both which they saw; for they told me they saw the smoke, though they did not hear the gun. Upon these signals they very kindly brought to, and lay by for me; and in about three hours; time I came up with them. \n"
					"They asked me what I was, in Portuguese, and in Spanish, and in French, but I understood none of them; but at last a Scotch sailor, who was on board, called to me: and I answered him, and told him I was an Englishman, that I had made my escape out of slavery from the Moors, at Sallee; they then bade me come on board, and very kindly took me in, and all my goods. \n"
					"It was an inexpressible joy to me, which any one will believe, that I was thus delivered, as I esteemed it, from such a miserable and almost hopeless condition as I was in; and I immediately offered all I had to the captain of the ship, as a return for my deliverance; but he generously told me he would take nothing from me, but that all I had should be delivered safe to me when I came to the Brazils. “For,” says he, “I have saved your life on no other terms than I would be glad to be saved myself: and it may, one time or other, be my lot to be taken up in the same condition. Besides,” said he, “when I carry you to the Brazils, so great a way from your own country, if I should take from you what you have, you will be starved there, and then I only take away that life I have given. No, no,” says he: “Seignior Inglese” (Mr. Englishman), “I will carry you thither in charity, and those things will help to buy your subsistence there, and your passage home again.” \n"
					"As he was charitable in this proposal, so he was just in the performance to a tittle; for he ordered the seamen that none should touch anything that I had: then he took everything into his own possession, and gave me back an exact inventory of them, that I might have them, even to my three earthen jars. \n"
					"As to my boat, it was a very good one; and that he saw, and told me he would buy it of me for his ship’s use; and asked me what I would have for it? I told him he had been so generous to me in everything that I could not offer to make any price of the boat, but left it entirely to him: upon which he told me he would give me a note of hand to pay me eighty pieces of eight for it at Brazil; and when it came there, if any one offered to give more, he would make it up. He offered me also sixty pieces of eight more for my boy Xury, which I was loth to take; not that I was unwilling to let the captain have him, but I was very loth to sell the poor boy’s liberty, who had assisted me so faithfully in procuring my own. However, when I let him know my reason, he owned it to be just, and offered me this medium, that he would give the boy an obligation to set him free in ten years, if he turned Christian: upon this, and Xury saying he was willing to go to him, I let the captain have him. \n"
					"We had a very good voyage to the Brazils, and I arrived in the Bay de Todos los Santos, or All Saints’ Bay, in about twenty-two days after. And now I was once more delivered from the most miserable of all conditions of life; and what to do next with myself I was to consider. \n"
					"The generous treatment the captain gave me I can never enough remember: he would take nothing of me for my passage, gave me twenty ducats for the leopard’s skin, and forty for the lion’s skin, which I had in my boat, and caused everything I had in the ship to be punctually delivered to me; and what I was willing to sell he bought of me, such as the case of bottles, two of my guns, and a piece of the lump of beeswax—for I had made candles of the rest: in a word, I made about two hundred and twenty pieces of eight of all my cargo; and with this stock I went on shore in the Brazils. \n"
					"I had not been long here before I was recommended to the house of a good honest man like himself, who had an ingenio, as they call it (that is, a plantation and a sugar-house). I lived with him some time, and acquainted myself by that means with the manner of planting and making of sugar; and seeing how well the planters lived, and how they got rich suddenly, I resolved, if I could get a licence to settle there, I would turn planter among them: resolving in the meantime to find out some way to get my money, which I had left in London, remitted to me. To this purpose, getting a kind of letter of naturalisation, I purchased as much land that was uncured as my money would reach, and formed a plan for my plantation and settlement; such a one as might be suitable to the stock which I proposed to myself to receive from England. ";
const char *demo3 = "## FIRST WEEKS ON THE ISLAND\n\n"
					"When I waked it was broad day, the weather clear, and the storm abated, so that the sea did not rage and swell as before. But that which surprised me most was, that the ship was lifted off in the night from the sand where she lay by the swelling of the tide, and was driven up almost as far as the rock which I at first mentioned, where I had been so bruised by the wave dashing me against it. This being within about a mile from the shore where I was, and the ship seeming to stand upright still, I wished myself on board, that at least I might save some necessary things for my use. \n"
					"When I came down from my apartment in the tree, I looked about me again, and the first thing I found was the boat, which lay, as the wind and the sea had tossed her up, upon the land, about two miles on my right hand. I walked as far as I could upon the shore to have got to her; but found a neck or inlet of water between me and the boat which was about half a mile broad; so I came back for the present, being more intent upon getting at the ship, where I hoped to find something for my present subsistence. \n"
					"A little after noon I found the sea very calm, and the tide ebbed so far out that I could come within a quarter of a mile of the ship. And here I found a fresh renewing of my grief; for I saw evidently that if we had kept on board we had been all safe—that is to say, we had all got safe on shore, and I had not been so miserable as to be left entirely destitute of all comfort and company as I now was. This forced tears to my eyes again; but as there was little relief in that, I resolved, if possible, to get to the ship; so I pulled off my clothes—for the weather was hot to extremity—and took the water. But when I came to the ship my difficulty was still greater to know how to get on board; for, as she lay aground, and high out of the water, there was nothing within my reach to lay hold of. I swam round her twice, and the second time I spied a small piece of rope, which I wondered I did not see at first, hung down by the fore-chains so low, as that with great difficulty I got hold of it, and by the help of that rope I got up into the forecastle of the ship. Here I found that the ship was bulged, and had a great deal of water in her hold, but that she lay so on the side of a bank of hard sand, or, rather earth, that her stern lay lifted up upon the bank, and her head low, almost to the water. By this means all her quarter was free, and all that was in that part was dry; for you may be sure my first work was to search, and to see what was spoiled and what was free. And, first, I found that all the ship’s provisions were dry and untouched by the water, and being very well disposed to eat, I went to the bread room and filled my pockets with biscuit, and ate it as I went about other things, for I had no time to lose. I also found some rum in the great cabin, of which I took a large dram, and which I had, indeed, need enough of to spirit me for what was before me. Now I wanted nothing but a boat to furnish myself with many things which I foresaw would be very necessary to me. \n"
					"It was in vain to sit still and wish for what was not to be had; and this extremity roused my application. We had several spare yards, and two or three large spars of wood, and a spare topmast or two in the ship; I resolved to fall to work with these, and I flung as many of them overboard as I could manage for their weight, tying every one with a rope, that they might not drive away. When this was done I went down the ship’s side, and pulling them to me, I tied four of them together at both ends as well as I could, in the form of a raft, and laying two or three short pieces of plank upon them crossways, I found I could walk upon it very well, but that it was not able to bear any great weight, the pieces being too light. So I went to work, and with a carpenter’s saw I cut a spare topmast into three lengths, and added them to my raft, with a great deal of labour and pains. But the hope of furnishing myself with necessaries encouraged me to go beyond what I should have been able to have done upon another occasion. \n"
					"My raft was now strong enough to bear any reasonable weight. My next care was what to load it with, and how to preserve what I laid upon it from the surf of the sea; but I was not long considering this. I first laid all the planks or boards upon it that I could get, and having considered well what I most wanted, I got three of the seamen’s chests, which I had broken open, and emptied, and lowered them down upon my raft; the first of these I filled with provisions—viz. bread, rice, three Dutch cheeses, five pieces of dried goat’s flesh (which we lived much upon), and a little remainder of European corn, which had been laid by for some fowls which we brought to sea with us, but the fowls were killed. There had been some barley and wheat together; but, to my great disappointment, I found afterwards that the rats had eaten or spoiled it all. As for liquors, I found several, cases of bottles belonging to our skipper, in which were some cordial waters; and, in all, about five or six gallons of rack. These I stowed by themselves, there being no need to put them into the chest, nor any room for them. While I was doing this, I found the tide begin to flow, though very calm; and I had the mortification to see my coat, shirt, and waistcoat, which I had left on the shore, upon the sand, swim away. As for my breeches, which were only linen, and open-kneed, I swam on board in them and my stockings. However, this set me on rummaging for clothes, of which I found enough, but took no more than I wanted for present use, for I had others things which my eye was more upon—as, first, tools to work with on shore. And it was after long searching that I found out the carpenter’s chest, which was, indeed, a very useful prize to me, and much more valuable than a shipload of gold would have been at that time. I got it down to my raft, whole as it was, without losing time to look into it, for I knew in general what it contained. \n"
					"\n---\nMy next care was for some ammunition and arms. There were two very good fowling-pieces in the great cabin, and two pistols. These I secured first, with some powder-horns and a small bag of shot, and two old rusty swords. I knew there were three barrels of powder in the ship, but knew not where our gunner had stowed them; but with much search I found them, two of them dry and good, the third had taken water. Those two I got to my raft with the arms. And now I thought myself pretty well freighted, and began to think how I should get to shore with them, having neither sail, oar, nor rudder; and the least capful of wind would have overset all my navigation. \n"
					"I had three encouragements—1st, a smooth, calm sea; 2ndly, the tide rising, and setting in to the shore; 3rdly, what little wind there was blew me towards the land. And thus, having found two or three broken oars belonging to the boat—and, besides the tools which were in the chest, I found two saws, an axe, and a hammer; with this cargo I put to sea. For a mile or thereabouts my raft went very well, only that I found it drive a little distant from the place where I had landed before; by which I perceived that there was some indraft of the water, and consequently I hoped to find some creek or river there, which I might make use of as a port to get to land with my cargo. \n"
					"As I imagined, so it was. There appeared before me a little opening of the land, and I found a strong current of the tide set into it; so I guided my raft as well as I could, to keep in the middle of the stream. \n"
					"But here I had like to have suffered a second shipwreck, which, if I had, I think verily would have broken my heart; for, knowing nothing of the coast, my raft ran aground at one end of it upon a shoal, and not being aground at the other end, it wanted but a little that all my cargo had slipped off towards the end that was afloat, and to fallen into the water. I did my utmost, by setting my back against the chests, to keep them in their places, but could not thrust off the raft with all my strength; neither durst I stir from the posture I was in; but holding up the chests with all my might, I stood in that manner near half-an-hour, in which time the rising of the water brought me a little more upon a level; and a little after, the water still-rising, my raft floated again, and I thrust her off with the oar I had into the channel, and then driving up higher, I at length found myself in the mouth of a little river, with land on both sides, and a strong current of tide running up. I looked on both sides for a proper place to get to shore, for I was not willing to be driven too high up the river: hoping in time to see some ships at sea, and therefore resolved to place myself as near the coast as I could. \n"
					"At length I spied a little cove on the right shore of the creek, to which with great pain and difficulty I guided my raft, and at last got so near that, reaching ground with my oar, I could thrust her directly in. But here I had like to have dipped all my cargo into the sea again; for that shore lying pretty steep—that is to say sloping—there was no place to land, but where one end of my float, if it ran on shore, would lie so high, and the other sink lower, as before, that it would endanger my cargo again. All that I could do was to wait till the tide was at the highest, keeping the raft with my oar like an anchor, to hold the side of it fast to the shore, near a flat piece of ground, which I expected the water would flow over; and so it did. As soon as I found water enough—for my raft drew about a foot of water—I thrust her upon that flat piece of ground, and there fastened or moored her, by sticking my two broken oars into the ground, one on one side near one end, and one on the other side near the other end; and thus I lay till the water ebbed away, and left my raft and all my cargo safe on shore. \n"
					"My next work was to view the country, and seek a proper place for my habitation, and where to stow my goods to secure them from whatever might happen. Where I was, I yet knew not; whether on the continent or on an island; whether inhabited or not inhabited; whether in danger of wild beasts or not. There was a hill not above a mile from me, which rose up very steep and high, and which seemed to overtop some other hills, which lay as in a ridge from it northward. I took out one of the fowling-pieces, and one of the pistols, and a horn of powder; and thus armed, I travelled for discovery up to the top of that hill, where, after I had with great labour and difficulty got to the top, I saw my fate, to my great affliction—viz. that I was in an island environed every way with the sea: no land to be seen except some rocks, which lay a great way off; and two small islands, less than this, which lay about three leagues to the west. \n"
					"I found also that the island I was in was barren, and, as I saw good reason to believe, uninhabited except by wild beasts, of whom, however, I saw none. Yet I saw abundance of fowls, but knew not their kinds; neither when I killed them could I tell what was fit for food, and what not. At my coming back, I shot at a great bird which I saw sitting upon a tree on the side of a great wood. I believe it was the first gun that had been fired there since the creation of the world. I had no sooner fired, than from all parts of the wood there arose an innumerable number of fowls, of many sorts, making a confused screaming and crying, and every one according to his usual note, but not one of them of any kind that I knew. As for the creature I killed, I took it to be a kind of hawk, its colour and beak resembling it, but it had no talons or claws more than common. Its flesh was carrion, and fit for nothing. \n"
					"Contented with this discovery, I came back to my raft, and fell to work to bring my cargo on shore, which took me up the rest of that day. What to do with myself at night I knew not, nor indeed where to rest, for I was afraid to lie down on the ground, not knowing but some wild beast might devour me, though, as I afterwards found, there was really no need for those fears. \n"
					"However, as well as I could, I barricaded myself round with the chest and boards that I had brought on shore, and made a kind of hut for that night’s lodging. As for food, I yet saw not which way to supply myself, except that I had seen two or three creatures like hares run out of the wood where I shot the fowl. ";
const char *demo4 = "## CHAPTER V. BUILDS A HOUSE—THE JOURNAL\n"
					"\n"
					"September 30, 1659.—I, poor miserable Robinson Crusoe, being shipwrecked during a dreadful storm in the offing, came on shore on this dismal, unfortunate island, which I called “The Island of Despair”; all the rest of the ship’s company being drowned, and myself almost dead. \n"
					"All the rest of the day I spent in afflicting myself at the dismal circumstances I was brought to—viz. I had neither food, house, clothes, weapon, nor place to fly to; and in despair of any relief, saw nothing but death before me—either that I should be devoured by wild beasts, murdered by savages, or starved to death for want of food. At the approach of night I slept in a tree, for fear of wild creatures; but slept soundly, though it rained all night. \n"
					"October 1.—In the morning I saw, to my great surprise, the ship had floated with the high tide, and was driven on shore again much nearer the island; which, as it was some comfort, on one hand—for, seeing her set upright, and not broken to pieces, I hoped, if the wind abated, I might get on board, and get some food and necessaries out of her for my relief—so, on the other hand, it renewed my grief at the loss of my comrades, who, I imagined, if we had all stayed on board, might have saved the ship, or, at least, that they would not have been all drowned as they were; and that, had the men been saved, we might perhaps have built us a boat out of the ruins of the ship to have carried us to some other part of the world. I spent great part of this day in perplexing myself on these things; but at length, seeing the ship almost dry, I went upon the sand as near as I could, and then swam on board. This day also it continued raining, though with no wind at all. \n"
					"From the 1st of October to the 24th.—All these days entirely spent in many several voyages to get all I could out of the ship, which I brought on shore every tide of flood upon rafts. Much rain also in the days, though with some intervals of fair weather; but it seems this was the rainy season. \n"
					"Oct. 20.—I overset my raft, and all the goods I had got upon it; but, being in shoal water, and the things being chiefly heavy, I recovered many of them when the tide was out. \n"
					"Oct. 25.—It rained all night and all day, with some gusts of wind; during which time the ship broke in pieces, the wind blowing a little harder than before, and was no more to be seen, except the wreck of her, and that only at low water. I spent this day in covering and securing the goods which I had saved, that the rain might not spoil them. \n"
					"\n---\nOct. 26.—I walked about the shore almost all day, to find out a place to fix my habitation, greatly concerned to secure myself from any attack in the night, either from wild beasts or men. Towards night, I fixed upon a proper place, under a rock, and marked out a semicircle for my encampment; which I resolved to strengthen with a work, wall, or fortification, made of double piles, lined within with cables, and without with turf. \n"
					"From the 26th to the 30th I worked very hard in carrying all my goods to my new habitation, though some part of the time it rained exceedingly hard. \n"
					"The 31st, in the morning, I went out into the island with my gun, to seek for some food, and discover the country; when I killed a she-goat, and her kid followed me home, which I afterwards killed also, because it would not feed. \n"
					"November 1.—I set up my tent under a rock, and lay there for the first night; making it as large as I could, with stakes driven in to swing my hammock upon. \n"
					"Nov. 2.—I set up all my chests and boards, and the pieces of timber which made my rafts, and with them formed a fence round me, a little within the place I had marked out for my fortification. \n"
					"Nov. 3.—I went out with my gun, and killed two fowls like ducks, which were very good food. In the afternoon went to work to make me a table. \n"
					"Nov. 4.—This morning I began to order my times of work, of going out with my gun, time of sleep, and time of diversion—viz. every morning I walked out with my gun for two or three hours, if it did not rain; then employed myself to work till about eleven o’clock; then eat what I had to live on; and from twelve to two I lay down to sleep, the weather being excessively hot; and then, in the evening, to work again. The working part of this day and of the next were wholly employed in making my table, for I was yet but a very sorry workman, though time and necessity made me a complete natural mechanic soon after, as I believe they would do any one else. \n"
					"Nov. 5.—This day went abroad with my gun and my dog, and killed a wild cat; her skin pretty soft, but her flesh good for nothing; every creature that I killed I took of the skins and preserved them. Coming back by the sea-shore, I saw many sorts of sea-fowls, which I did not understand; but was surprised, and almost frightened, with two or three seals, which, while I was gazing at, not well knowing what they were, got into the sea, and escaped me for that time. \n"
					"Nov. 6.—After my morning walk I went to work with my table again, and finished it, though not to my liking; nor was it long before I learned to mend it. \n"
					"Nov. 7.—Now it began to be settled fair weather. The 7th, 8th, 9th, 10th, and part of the 12th (for the 11th was Sunday) I took wholly up to make me a chair, and with much ado brought it to a tolerable shape, but never to please me; and even in the making I pulled it in pieces several times. \n"
					"Note.—I soon neglected my keeping Sundays; for, omitting my mark for them on my post, I forgot which was which. \n"
					"Nov. 13.—This day it rained, which refreshed me exceedingly, and cooled the earth; but it was accompanied with terrible thunder and lightning, which frightened me dreadfully, for fear of my powder. As soon as it was over, I resolved to separate my stock of powder into as many little parcels as possible, that it might not be in danger. \n"
					"Nov. 14, 15, 16.—These three days I spent in making little square chests, or boxes, which might hold about a pound, or two pounds at most, of powder; and so, putting the powder in, I stowed it in places as secure and remote from one another as possible. On one of these three days I killed a large bird that was good to eat, but I knew not what to call it. \n"
					"Nov. 17.—This day I began to dig behind my tent into the rock, to make room for my further conveniency. \n"
					"Note.—Three things I wanted exceedingly for this work—viz. a pickaxe, a shovel, and a wheelbarrow or basket; so I desisted from my work, and began to consider how to supply that want, and make me some tools. As for the pickaxe, I made use of the iron crows, which were proper enough, though heavy; but the next thing was a shovel or spade; this was so absolutely necessary, that, indeed, I could do nothing effectually without it; but what kind of one to make I knew not. \n"
					"Nov. 18.—The next day, in searching the woods, I found a tree of that wood, or like it, which in the Brazils they call the iron-tree, for its exceeding hardness. Of this, with great labour, and almost spoiling my axe, I cut a piece, and brought it home, too, with difficulty enough, for it was exceeding heavy. The excessive hardness of the wood, and my having no other way, made me a long while upon this machine, for I worked it effectually by little and little into the form of a shovel or spade; the handle exactly shaped like ours in England, only that the board part having no iron shod upon it at bottom, it would not last me so long; however, it served well enough for the uses which I had occasion to put it to; but never was a shovel, I believe, made after that fashion, or so long in making. \n"
					"I was still deficient, for I wanted a basket or a wheelbarrow. A basket I could not make by any means, having no such things as twigs that would bend to make wicker-ware—at least, none yet found out; and as to a wheelbarrow, I fancied I could make all but the wheel; but that I had no notion of; neither did I know how to go about it; besides, I had no possible way to make the iron gudgeons for the spindle or axis of the wheel to run in; so I gave it over, and so, for carrying away the earth which I dug out of the cave, I made me a thing like a hod which the labourers carry mortar in when they serve the bricklayers. This was not so difficult to me as the making the shovel: and yet this and the shovel, and the attempt which I made in vain to make a wheelbarrow, took me up no less than four days—I mean always excepting my morning walk with my gun, which I seldom failed, and very seldom failed also bringing home something fit to eat. \n"
					"Nov. 23.—My other work having now stood still, because of my making these tools, when they were finished I went on, and working every day, as my strength and time allowed, I spent eighteen days entirely in widening and deepening my cave, that it might hold my goods commodiously. \n"
					"Note.—During all this time I worked to make this room or cave spacious enough to accommodate me as a warehouse or magazine, a kitchen, a dining-room, and a cellar. As for my lodging, I kept to the tent; except that sometimes, in the wet season of the year, it rained so hard that I could not keep myself dry, which caused me afterwards to cover all my place within my pale with long poles, in the form of rafters, leaning against the rock, and load them with flags and large leaves of trees, like a thatch. \n"
					"December 10.—I began now to think my cave or vault finished, when on a sudden (it seems I had made it too large) a great quantity of earth fell down from the top on one side; so much that, in short, it frighted me, and not without reason, too, for if I had been under it, I had never wanted a gravedigger. I had now a great deal of work to do over again, for I had the loose earth to carry out; and, which was of more importance, I had the ceiling to prop up, so that I might be sure no more would come down. \n"
					"Dec. 11.—This day I went to work with it accordingly, and got two shores or posts pitched upright to the top, with two pieces of boards across over each post; this I finished the next day; and setting more posts up with boards, in about a week more I had the roof secured, and the posts, standing in rows, served me for partitions to part off the house. \n"
					"Dec. 17.—From this day to the 20th I placed shelves, and knocked up nails on the posts, to hang everything up that could be hung up; and now I began to be in some order within doors. \n"
					"Dec. 20.—Now I carried everything into the cave, and began to furnish my house, and set up some pieces of boards like a dresser, to order my victuals upon; but boards began to be very scarce with me; also, I made me another table. \n"
					"Dec. 24.—Much rain all night and all day. No stirring out. \n"
					"Dec. 25.—Rain all day. \n"
					"Dec. 26.—No rain, and the earth much cooler than before, and pleasanter. \n"
					"Dec. 27.—Killed a young goat, and lamed another, so that I caught it and led it home in a string; when I had it at home, I bound and splintered up its leg, which was broke. \n"
					"N.B.—I took such care of it that it lived, and the leg grew well and as strong as ever; but, by my nursing it so long, it grew tame, and fed upon the little green at my door, and would not go away. This was the first time that I entertained a thought of breeding up some tame creatures, that I might have food when my powder and shot was all spent. \n"
					"Dec. 28, 29, 30.—Great heats and no breeze, so that there was no stirring abroad except in the evening for food; this time I spent in putting all my things in order within doors. \n"
					"January 1.—Very hot still: but I went abroad early and late with my gun, and lay still in the middle of the day. This evening, going farther into the valleys which lay towards the centre of the island, I found there were plenty of goats, though exceedingly shy, and hard to come at; however, I resolved to try if I could not bring my dog to hunt them down. \n"
					"Jan. 2.—Accordingly, the next day I went out with my dog, and set him upon the goats, but I was mistaken, for they all faced about upon the dog, and he knew his danger too well, for he would not come near them. \n"
					"Jan. 3.—I began my fence or wall; which, being still jealous of my being attacked by somebody, I resolved to make very thick and strong. \n"
					"N.B.—This wall being described before, I purposely omit what was said in the journal; it is sufficient to observe, that I was no less time than from the 2nd of January to the 14th of April working, finishing, and perfecting this wall, though it was no more than about twenty-four yards in length, being a half-circle from one place in the rock to another place, about eight yards from it, the door of the cave being in the centre behind it. \n"
					"All this time I worked very hard, the rains hindering me many days, nay, sometimes weeks together; but I thought I should never be perfectly secure till this wall was finished; and it is scarce credible what inexpressible labour everything was done with, especially the bringing piles out of the woods and driving them into the ground; for I made them much bigger than I needed to have done. ";
